### PR TITLE
Changed Dockerfile to Node:18-slim (Fixing #1865)

### PR DESCRIPTION
**Pull request by BE-CH**
I changed to ``node:18-slim`` in the Dockerfile for all the stages. 

This fixes the issue #1865 

_This does increase image size around ~ 100 MB but fixes the problem until https://github.com/prisma/prisma/issues/18510 is fixed from the prisma team_

@mikecao

### CODE REVIEW

**Comment by busybox11** [comment]
I can't get this PR to properly build on my Portainer instance. Do you have to do anything particular in order to get it to work? It returns nothing in my container logs and does not seem to be assigned to the correct container image, though I am unsure what to do in this case.

**Comment by BE-CH** [comment]
@busybox11 Hmm.. not anything specific. The only change is just the base image.  Maybe there is some caching issues?

**Comment by busybox11** [comment]
I try to build the image and run it like the dockerhub one but it doesn't run anything - just an empty shell. It could very well be an issue on my end but tbh I'm not quite sure what to do - it works with the original image. Could this be related to ARM64?

**Comment by orgarten** [comment]
I just build the Dockerfile and it works for me. The only thing that I missed was to specify `DATABASE_TYPE` in `--build-arg` when building the image. I also build on ARM64

@busybox11: it sounds like your build succeeds but you just get an empty shell? Can you post your build logs?

**Pull request closed without merging**
