### PR TITLE
Fix 'Error loading shared library libssl.so.1.1' error

### PR DESCRIPTION
**Pull request by elvisvoer**
Fixes the error as per indicated solution found here: https://github.com/prisma/prisma/issues/16553#issuecomment-1348473683

### CODE REVIEW

**Comment by svargas-dev** [comment]
As a side note, I also fixed this in my fork by updating prisma dependencies ("@prisma/client" & "prisma") to ^4.8 instead of 4.50 and changing line 4 of the Dockerfile to:

`RUN apk add --no-cache libc6-compat openssl openssl-dev`

I'm not sure openssl-dev is required but I haven't had time to look deeper into this.

**Comment by svargas-dev** [comment]
I've opened another PR that addresses this issue with Prisma 4.8x #1728

**Comment by ebauger** [comment]
I did resolve by removing the lock file and update the prisma and @prisma/client dep and in the Dockerfile


Dockerfile working on Railway.
```
# Install dependencies only when needed
FROM node:16-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat openssl openssl-dev
WORKDIR /app
COPY package.json ./
RUN yarn install

# Rebuild the source code only when needed
FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG DATABASE_TYPE
ARG BASE_PATH

ENV DATABASE_TYPE $DATABASE_TYPE
ENV BASE_PATH $BASE_PATH

ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build-docker

# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

RUN yarn add npm-run-all dotenv prisma@^4.8

# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /app/next.config.js .
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/scripts ./scripts

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "start-docker"]
```

**Comment by gregonarash** [comment]
> I did resolve by removing the lock file and update the prisma and @prisma/client dep and in the Dockerfile
> 
> Dockerfile working on Railway with release [v1.39.5](https://github.com/umami-software/umami)
> 
> ```
> # Install dependencies only when needed
> FROM node:16-alpine AS deps
> # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
> RUN apk add --no-cache libc6-compat openssl openssl-dev
> WORKDIR /app
> COPY package.json ./
> RUN yarn install
> 
> # Rebuild the source code only when needed
> FROM node:16-alpine AS builder
> WORKDIR /app
> COPY --from=deps /app/node_modules ./node_modules
> COPY . .
> 
> ARG DATABASE_TYPE
> ARG BASE_PATH
> 
> ENV DATABASE_TYPE $DATABASE_TYPE
> ENV BASE_PATH $BASE_PATH
> 
> ENV NEXT_TELEMETRY_DISABLED 1
> 
> RUN yarn build-docker
> 
> # Production image, copy all the files and run next
> FROM node:16-alpine AS runner
> WORKDIR /app
> 
> ENV NODE_ENV production
> ENV NEXT_TELEMETRY_DISABLED 1
> 
> RUN addgroup --system --gid 1001 nodejs
> RUN adduser --system --uid 1001 nextjs
> 
> RUN yarn add npm-run-all dotenv prisma@^4.8
> 
> # You only need to copy next.config.js if you are NOT using the default configuration
> COPY --from=builder /app/next.config.js .
> COPY --from=builder --chown=nextjs:nodejs /app/public ./public
> COPY --from=builder /app/package.json ./package.json
> COPY --from=builder /app/prisma ./prisma
> COPY --from=builder /app/scripts ./scripts
> 
> # Automatically leverage output traces to reduce image size
> # https://nextjs.org/docs/advanced-features/output-file-tracing
> COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
> COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
> 
> USER nextjs
> 
> EXPOSE 3000
> 
> ENV PORT 3000
> 
> CMD ["yarn", "start-docker"]
> ```

for me the your Docker and  updating prisima in package.json to 4.8.0  did the job. 

This should be updated in main repo

**Pull request closed without merging**
