### PR TITLE
[Updated] The css of the div was fixed.

### PR DESCRIPTION
**Pull request by 0amirk**
#### Screenshots for the same are as follows:

Mobile view:
Screenshot (62)

Little bigger mobile view (448px):
Screenshot (63)

Tablet view:
Screenshot (64)

Desktop view:
Screenshot (66)

### CODE REVIEW

**Comment by 0amirk** [comment]
@mikecao please review this pr.

**Comment by timonson** [comment]
Thank you @0amirk , it looks great!

**Review by Dandrum — APPROVED** [review]

**Review by mikecao — APPROVED** [review]

**Comment by mikecao** [comment]
Looks good, but you'll have to resolve the merge conflicts.

**Comment by 0amirk** [comment]
@mikecao Thank you for your reply but I'm not even sure what to do anymore. I just checked out the current code of umami and all the files have changed. Does this issue still persist ? What should I do?

**Comment by mikecao** [comment]
This should already be fixed in the current version.

**Pull request closed without merging**
