### PR TITLE
feat: add client screen size statics

### PR DESCRIPTION
**Pull request by serkon**
Track Screen Resolution #469

I have added also screen sizes to my UI. 
Solution: https://github.com/mikecao/umami/issues/469#issuecomment-991977182

### CODE REVIEW

**Comment by quickstar** [comment]
Thank you for this feature! Exactly what I was looking for! Hopefully this gets merged pretty soon :rocket:

**Comment by mikecao** [comment]
I'd rather not have another table to display screen sizes since it will take up too much room. But we can put it under a tab in `More` section like we do for languages.

**Comment by thueske** [comment]
https://github.com/umami-software/umami/pull/1304

**Comment by mikecao** [comment]
Completed in #1304

**Pull request closed without merging**
