### PR TITLE
fix TRACKER_SCRIPT_NAME in v2

### PR DESCRIPTION
**Pull request by Slowlydev**
fix of  #1891

used this piece of the v1 code
https://github.com/umami-software/umami/blob/cc2be9f47a2276ef590b6f3ae5f1d25652a912d6/middleware.js#L21-L34

### CODE REVIEW

**Comment by DCi-dev** [comment]
Great job! It works. 

As an idea, the only thing that's missing is updating the TRACKER_SCRIPT_URL constant in the lib/constants.ts or in components/pages/settings/website/TrackingCode.js, so that any changes would reflect in the Settings>Website>Tracking code, on the live instance.

**Comment by rohandebsarkar** [comment]
Maybe a better approach would be to use Next.js rewrites instead of using middleware.

https://github.com/rohandebsarkar/umami/blob/b9c2ed882e813b98c11a504343787e75dfe483cd/next.config.js#L47-L59

**Comment by Slowlydev** [comment]
Oh Yeah I agree didn't know about rewrites yet and that u started using them in v2 already, I just looked at the v1 code and re-implemented that. 

I updated the PR with the rewrites and made some adjustments to your approach.

**Comment by MBRjun** [comment]
Thank you! The code is working well.

```
$ curl 127.0.0.1:53019/delightful.js?v=2.0.0-1 -I

HTTP/1.1 200 OK
```

**Review by MBRjun — APPROVED** [review]

**Comment by Slowlydev** [comment]
It seems this got fixed in following commit https://github.com/umami-software/umami/commit/ac8d8bbd1e6b28a4bb8a6eda67d5243339eacc47  so this PR for now is not needed anymore. One thing to note that the mentioned commit needs the users to change their env var and we also loose the option to add multiple script names.

**Comment by mikecao** [comment]
Fixed in v2.0.1

**Pull request closed without merging**
