### PR TITLE
feat: Add support for hash-based routing tracking

### PR DESCRIPTION
**Pull request by DDDDD12138**
Fix: #2954 

#### Changes
- Added support for hash-based routing to ensure proper URL parsing.
- Used `location.origin` as the base to ensure relative paths are correctly processed.

#### Before
image

#### After
image

### CODE REVIEW

**Comment by mikecao** [comment]
It looks like this does the same thing as the original, which is to extract the path from the URL.

**Comment by DDDDD12138** [comment]
> It looks like this does the same thing as the original, which is to extract the path from the URL.

Yes, I'm essentially following the original approach.
Previously, only concatenated the `pathname` and `search`, which caused the `hash` to be lost.  Now, by removing the `origin` from the `href`, ensured that the final `url` variable's value is complete

**Comment by mikecao** [comment]
The URL object provides a `hash` property, so you can just do

```
const {pathname, search, hash} = new URL(url, location.origin);
url = pathname + search + hash;
```

**Comment by DDDDD12138** [comment]
@mikecao You are right. I was overthinking it. I have already made the changes based on your suggestions.

**Review by mikecao — APPROVED** [review]
👍

**Pull request merged**
