### PR TITLE
Allow embedding of "Share" dashboard as iframe

### PR DESCRIPTION
**Pull request by bdcorps**
- This PR adds a `EMBED_HOSTED_URL` environment that lets a user load up the "Share" dashboard view inside their own applications as an iframe.
- Fixes https://github.com/umami-software/umami/issues/1802

## How to use: 
1. Add an environment variable called: `EMBED_HOSTED_URL` with value `http://app.localhost:7000`. Replace the URL with host/port from wherever your frontend app is running.
2. Add an iframe like so: `<iframe src="https://umami-analytics-pi.vercel.app/share/<shareid>" width="100%" height={2800}></iframe>`. Replace `shareid` with the share ID of the Dashboard you want to view.
3. The Analytics report should load without any errors in the console.
image

### CODE REVIEW

**Comment by ccfiel** [comment]
any update on this?

**Review by mikecao — APPROVED** [review]
👍

**Comment by 0x7466** [comment]
This is `ALLOWED_FRAME_URLS` now.

**Comment by JW148** [comment]
I have been trying to embed the Umami dashboard through the share URL after setting the `ALLOWED_FRAME_URLS` build variable but keep getting a 'refused to connect' error in my embedded iFrame. For context, I am self hosting on Coolify.

**Comment by zcraber** [comment]
> I have been trying to embed the Umami dashboard through the share URL after setting the `ALLOWED_FRAME_URLS` build variable but keep getting a 'refused to connect' error in my embedded iFrame. I can also see that frame-ancestors 'self' is undefined from the iFrame header response. 

Experiencing the same. Did you find a solution for this?

**Comment by ghost** [comment]
Currently not working 

There is an feature request for this, having the same problem. 

To embed as iframe u need to build the image yourself. 



https://github.com/umami-software/umami/issues/3793

**Comment by zcraber** [comment]
> To embed as iframe u need to build the image yourself.

Found a workaround using header transform rules in Cloudflare.

**Pull request merged**
