### PR TITLE
Update Localisation for Swedish language

### PR DESCRIPTION
**Pull request by Braggedtooth**

### CODE REVIEW

**Comment by mikecao** [comment]
Hi @Braggedtooth, thanks for this contribution! But the correct file to change is under `/src/lang`. The file under `public` is the compiled file.

**Comment by Braggedtooth** [comment]
> Hi @Braggedtooth, thanks for this contribution! But the correct file to change is under `/src/lang`. The file under `public` is the compiled file.

Oh my mistake, I will update the correct file and update the pr.

**Comment by Braggedtooth** [comment]
Do you prefer a new PR or is it ok, if I revert the previous commit and make a new commit? @mikecao

**Comment by Braggedtooth** [comment]
Created a new PR #2447

**Pull request closed without merging**
