### PR TITLE
Roll back prisma to 4.9.0

### PR DESCRIPTION
**Pull request by anthonyalayo**
Fix for https://github.com/umami-software/umami/issues/1865

### CODE REVIEW

**Comment by anthonyalayo** [comment]
@mikecao can we merge this? It would help a lot of people

**Comment by uncenter** [comment]
Is this still an issue after upgrading to Prisma v5.0.0 in https://github.com/umami-software/umami/releases/tag/v2.4.0?

**Comment by uncenter** [comment]
I think this PR can be closed since Prisma was bumped to `5.3.1` in https://github.com/umami-software/umami/releases/tag/v2.7.0, which should *finally* make Umami run in ARM servers.

**Comment by anthonyalayo** [comment]
Agreed

**Pull request closed without merging**
