### PR TITLE
Adds 'Direct / None' referrer when no referrer is present

### LINKED ISSUE #1223: No referrer/Direct visits
Currently, we can't filter the direct visits (without referrer), nor view the amount of them.

Plausible has a Direct / None source
[https://plausible.io/plausible.io?source=Direct+%2F+None](https://plausible.io/plausible.io?source=Direct+%2F+None)

Could it be considered in Umami ?

### PR DESCRIPTION
**Pull request by rohandebsarkar**
resolves #1223

### CODE REVIEW

**Comment by rohandebsarkar** [comment]
Though this PR enters `Direct / None` in the databse when no referrer is avialable. This is not reflected in the dashboard. I tried to find what is wrong, but wasn't successful.

**Comment by Maxime-J** [comment]
Hello Rohan :) Interesting you went that way.
I think we shouldn't touch the database, it would grow it unnecessarily => that info is already present (pageviews with blank referrer).

**Comment by njfdev** [comment]
I am looking at a way to do this on the frontend instead of the backend. I'll let you know of my results.

**Comment by mikecao** [comment]
This is not an ideal solution. I would rather it all be handled by the frontend.

**Comment by njfdev** [comment]
This has been solved on the front end. #1283

**Comment by rohandebsarkar** [comment]
@Maxime-J @njfdev @mikecao Yeah, I would agree doing this front end would be a better choice.

**Pull request closed without merging**
