### PR TITLE
Add ability to reorder websites on dashboard

### PR DESCRIPTION
**Pull request by cywio**
https://user-images.githubusercontent.com/51844916/180635011-5b928108-861b-471b-9ccd-a0b041d3372f.mov

Hello! Decided to take a shot at the re-ordering feature as mentioned in #1327, #1169 and #713. This implementation uses `localstorage` since that is what the language preference and theme uses, I figure it probably isn't worth adding to the database if language/theme isn't either. I've also added a reset button to reset back to alphabetical order. I had to add a dependency for dragging, but I hope that was alright.

Many thanks!

### CODE REVIEW

**Comment by mikecao** [comment]
This is really cool! Been meaning to revamp the dashboards for a while. However, an edit interface outside of website settings would be preferable, like `Edit Dashboard` in the same drop-down as `Toggle Charts`. That way users know they are only dealing with the dashboard specifically.

**Comment by cywio** [comment]
https://user-images.githubusercontent.com/51844916/180713647-49f7e83e-2815-42d8-81df-06cf03f10230.mp4

Hi, thanks for taking a look! I've reverted the settings page and moved it over to the dashboard under the drop-down like you said. I do have a question though, should we leave the settings page in alphabetical order or keep it the same order as the dashboard? It's a simple fix if we revert it back to alphabetical. I'll also take a look into the weird spacing issue while dragging and reanimation of the numbers when entering/exiting sometime tomorrow.

Thanks!

**Comment by MagicLike** [comment]
Sorry if I burst into this conversation, but if you have quite a large amount of websites on the Dashboard, it will be very annoying to drag website 1 from the top to the bottom and the other way around.
So I think it would be better if all the websites would collapse and only the titles are shown. That way there won't be that much clutter on the screen.

Sorry if I'm bursting into this conversation, but if you have a large number of websites on the dashboard, it would be very annoying to drag website 1 from the top to the bottom and vice versa.
So I think it would be better if all the websites would collapse and only the titles would be shown. That way there wouldn't be so much clutter on the screen.

**Comment by cywio** [comment]
https://user-images.githubusercontent.com/51844916/181657965-0a0ce002-6fc9-4c20-9136-e16e56480f7f.mov

Hello! I went ahead and fixed the graphical errors, no longer will the last element cause the parent container to be shorter, and the border's won't get stuck anymore. I also thought @MagicLike 's comment was a good idea so I implemented the charts hiding when in edit mode, but we can revert that with a simple change to line 89 in the website dashboard file.

Thanks!

**Comment by d19dotca** [comment]
That's awesome! Curious... Is it possible at all to have this auto-sort by number of visitors or views rather than having to order them manually? I think both options would be great but wondering how much extra it is to have it auto-sort based on certain fields displayed (i.e. views, visitors, bounce rate, etc).

**Pull request merged**
